title: Cybersecurity & Networking Projects
description: Welcome to my collection of hands-on cybersecurity and networking projects! Here, you will find real-world applications of Splunk Enterprise for powerful security monitoring and Splunk SOAR for automated incident response. From threat detection and log analysis to intrusion response and network defense, these projects showcase my ability to turn data into actionable security insights. Dive in to see how I leverage cutting-edge tools to strengthen cybersecurity and streamline operations!
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
